# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  redocly_linter:
    runs-on: ubuntu-latest
    container: node:latest
    env:
      APIQ_GITLAB_URL: ${{ secrets.APIQ_GITLAB_URL }}
      CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
      GITLAB_USER_EMAIL: ${{ secrets.GITLAB_USER_EMAIL }}
      GITLAB_USER_NAME: ${{ secrets.GITLAB_USER_NAME }}
      APIQ_API_FILENAME: "openapi.yaml"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load pipeline properties
        run: . pipeline.properties
        shell: bash

      - name: Set Git Safe Directory
        run: git config --global --add safe.directory $(pwd)

      - name: Configure Git
        run: |
          git config --global user.email "${GITLAB_USER_EMAIL}"
          git config --global user.name "${GITLAB_USER_NAME}"
          git checkout -f ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }}
          git pull

      - name: Install Redocly CLI
        run: npm install @redocly/cli -g
        if: contains(github.event.head_commit.message, 'redocly_linter')

      - name: Run Redocly Linter
        run: |
          mkdir -p auto-generated/redocly
          redocly lint $APIQ_API_FILENAME --format checkstyle > auto-generated/redocly/redocly_report.xml || LINT_EXIT_CODE=$?
          git add .
          if git diff-index --quiet HEAD --; then 
            echo "No changes to commit."
          else
            git commit -m "Generate redocly linter report"
            git push https://${{ secrets.CI_JOB_TOKEN }}@${{ secrets.APIQ_GITLAB_URL }}/${{ github.repository }}.git -o ci.skip
          fi
          exit $LINT_EXIT_CODE
        if: contains(github.event.head_commit.message, 'redocly_linter')
